#!/usr/bin/env python3
"""Put the Google tag in the real <head> of every page.

Squarespace injected the analytics tag itself, so the migration left the
GA4 property ("Paititi Institute - GA4") alive in Google's console but firing
on nothing: Google Ads reported the tag as *Not detected* when the Ad Grant
was set up. This restores it.

Why the real <head> and not <helmet>:

  <helmet> is appended to the head by support.js *at runtime*. That is fine for
  a browser, but Google's "is the tag installed?" check reads the HTML as it
  arrives. A tag that only exists after JavaScript has run can keep reporting
  Not detected even while it records traffic perfectly well — the same class of
  failure that hid the link previews from WhatsApp (see docs/seo.md). Loading
  it through a local wrapper file has the same problem, for the same reason:
  the snippet has to be visible in the page source.

Which id:

  GT-MBL4BMP is the *Google tag* — the container. G-CWC5ZQ8CMX is the GA4
  destination already attached to it. Loading the container means the Ads
  destination (AW-18415578586) starts firing the moment Roman connects Google
  Ads to this tag in the Ads UI, with no second snippet and no code change,
  which is exactly the plan. Configuring both ids here would double-count every
  page view, so don't.

    python3 tools/apply_analytics.py           # insert or refresh the block
    python3 tools/apply_analytics.py --check   # report drift, write nothing
    python3 tools/apply_analytics.py --remove  # take the tag back out

Idempotent, and safe to re-run. Run it LAST, after apply_head_meta.py, so a
later pass that rewrites <head> meta cannot land inside the block.

Not tagged, deliberately:
  rbg-widget.html   the Retreat Guru iframe — it loads *inside* a retreat page
                    that is already counted, so tagging it doubles every view
  islands-demo.html, motion-lab.html   development pages, not site content
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

TAG_ID = 'GT-MBL4BMP'          # the Google tag; GA4 G-CWC5ZQ8CMX hangs off it

BEGIN = '<!-- BEGIN google tag (generated by tools/apply_analytics.py) -->'
END = '<!-- END google tag -->'

BLOCK = f"""{BEGIN}
<script async src="https://www.googletagmanager.com/gtag/js?id={TAG_ID}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{dataLayer.push(arguments);}}
  gtag('js', new Date());

  gtag('config', '{TAG_ID}');
</script>
{END}"""

# Pages that are real destinations a visitor can land on. Everything else in
# the repo is either a fragment, a widget or a demo.
SKIP = {'rbg-widget.html', 'islands-demo.html', 'motion-lab.html'}

BLOCK_RE = re.compile(re.escape(BEGIN) + r'.*?' + re.escape(END) + r'\n?', re.S)
# Anchor after the charset declaration: it has to stay inside the first 1024
# bytes of the document or the browser guesses the encoding, and this snippet
# is big enough to push it out.
CHARSET_RE = re.compile(r'(<meta\s+charset=[^>]*>\n?)', re.I)
HEAD_RE = re.compile(r'(<head>\n?)', re.I)


def targets():
    out = [p for p in sorted(ROOT.glob('*.dc.html'))]
    for name in ('index.html', '404.html'):
        p = ROOT / name
        if p.exists():
            out.append(p)
    return [p for p in out if p.name not in SKIP]


def apply(src, remove=False):
    """Return the page with the block removed, refreshed, or inserted."""
    stripped = BLOCK_RE.sub('', src)
    if remove:
        return stripped
    if '<head>' not in stripped.lower():
        return None
    anchor = CHARSET_RE.search(stripped) or HEAD_RE.search(stripped)
    if not anchor:
        return None
    at = anchor.end()
    return stripped[:at] + BLOCK + '\n' + stripped[at:]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true', help='report drift, write nothing')
    ap.add_argument('--remove', action='store_true', help='take the tag back out')
    args = ap.parse_args()

    changed, skipped = [], []
    for path in targets():
        src = path.read_text(encoding='utf-8')
        new = apply(src, remove=args.remove)
        if new is None:
            skipped.append(path.name)
            continue
        if new != src:
            changed.append(path.name)
            if not args.check:
                path.write_text(new, encoding='utf-8')

    verb = 'drift' if args.check else ('removed' if args.remove else 'wrote')
    for name in changed:
        print('  %s: %s' % (verb, name))
    for name in skipped:
        print('  NO HEAD, skipped: %s' % name)
    if not changed:
        print('  everything already in step')
    else:
        print('  %d page(s), tag %s' % (len(changed), TAG_ID))
    return 1 if (args.check and changed) else 0


if __name__ == '__main__':
    sys.exit(main())
