#!/usr/bin/env python3
"""Put every page's title and social card where a link-preview crawler can see it.

Each page in this repo declares its `<title>`, description, canonical and Open
Graph tags inside `<x-dc><helmet>`, which is **in the body**. `support.js` moves
them into `document.head` when it renders. That is fine for anything that runs
JavaScript — Googlebot does — and useless for everything that does not, which is
every link-preview crawler there is: WhatsApp, iMessage, Slack, Facebook,
LinkedIn, Discord, Signal. So a link to any page of this site, pasted into a
chat, arrived as a bare URL: no title, no description, no image. The browser tab
showed the URL too, until the page rendered.

This moves those tags — and only those — out of `<helmet>` and into the real
`<head>`. Everything else (stylesheets, icons, the manifest, theme-color, the
page's own `<style>`) stays in `<helmet>`, where the runtime wants it.

    python3 tools/apply_head_meta.py            # move + generate the cards
    python3 tools/apply_head_meta.py --check    # report drift, change nothing

While it is there it repairs the three things that stop a card rendering even
once the tags are visible:

  * **`og:image` was a site-relative path.** The spec wants an absolute URL and
    several scrapers simply drop a relative one. Now absolute.
  * **The images are WebP.** LinkedIn and older Mail/Messages builds render
    nothing for a WebP card, so each one gets a JPEG derivative under
    `assets/social/`, longest side 1200. No crop: every scraper crops to its own
    frame, and cropping to 1.91:1 here would take the top off a portrait.
  * **The fourteen blog posts had no `og:image` at all** — the posts are the
    most-shared pages on the site. Each takes the first photograph in its own
    body, which is the one a reader would call that post's picture.

`og:url` and `twitter:card` are added where they were missing, after the
hreflang block so that `apply_hreflang.py` keeps its own insertion point.

Where this sits in the pipeline: it runs **last**, after `migrate_blog.py`,
`gen_responsive.py` and `apply_hreflang.py`, and it is idempotent, so re-running
it after any of them is the fix for the drift they cause. `migrate_blog.py
--check` imports `transform()` from here for exactly that reason, so its
byte-for-byte comparison stays honest. `gen_retreats.py` needs nothing from
here: it writes its pages this way already.
"""
import argparse
import os
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = 'https://paititi-institute.org'
SOCIAL_DIR = ROOT / 'assets' / 'social'
CARD_MAX = 1200
# What a page shares when it has no picture of its own — the home page's, so the
# fallback is the site's signature image rather than an arbitrary one.
DEFAULT_IMAGE = '/assets/home/screenshot-2025-04-12-at-70237e280afpm.webp'

NOTE = (
    '<!-- The title and the social card sit in the real <head>, not in <helmet>\n'
    '     below, and that is deliberate. <helmet> is appended to the head by\n'
    '     support.js *at runtime*; the crawlers that build a link preview —\n'
    '     WhatsApp, Messages, Slack, Facebook, LinkedIn — read the HTML as it\n'
    '     arrives and run no JavaScript, so meta left in <helmet> reaches none of\n'
    '     them and the link pastes as a bare URL. Generated by\n'
    '     tools/apply_head_meta.py; run it again after migrate_blog.py,\n'
    '     gen_responsive.py or apply_hreflang.py. -->'
)

# The tags a link preview and a search result are built from. Everything else
# stays in <helmet>: it only has to exist by the time the page renders.
MOVE = re.compile(
    r'^\s*(?:'
    r'<title>'
    r'|<meta\s+name="(?:description|robots|twitter:[^"]*)"'
    r'|<meta\s+property="(?:og:|article:)[^"]*"'
    r'|<link\s+rel="canonical"'
    r'|<link\s+rel="alternate"\s+hreflang='
    r')'
)
I18N_START = '<!-- i18n:hreflang'
I18N_END = '<!-- /i18n:hreflang -->'


def span(html, open_tag, close_tag):
    a = html.find(open_tag)
    b = html.find(close_tag, a + 1) if a != -1 else -1
    return (a, b) if a != -1 and b != -1 else None


def card_for(src):
    """/assets/home/paititi-lizpeace-63.webp -> /assets/social/home-paititi-lizpeace-63.jpg

    Deterministic, and computed whether or not the file exists yet, so that
    transform() stays a pure function of the HTML and `--check` can report a
    card that has gone missing rather than silently changing the tag back."""
    rel = src[len('/assets/'):]
    stem, _ = os.path.splitext(rel)
    return '/assets/social/' + stem.replace('/', '-') + '.jpg'


def first_body_image(html):
    """The first photograph in the page's own body — a blog post's picture."""
    body = html[html.find('</helmet>'):] if '</helmet>' in html else html
    m = re.search(r'<img\b[^>]*\bsrc="(/assets/[^"]+\.(?:webp|jpg|jpeg|png))"', body, re.I)
    return m.group(1) if m else None


def meta(prop, content, attr='property'):
    return '<meta %s="%s" content="%s">' % (attr, prop, content)


def transform(html, name=''):
    """Move the preview tags into <head> and complete the card. Pure and idempotent."""
    hd = span(html, '<head>', '</head>')
    if not hd:
        return html
    # Search for <helmet> only *after* </head>. The note this tool writes into
    # the head quotes the tag name, and finding that instead made the whole head
    # look like part of the helmet — so a second run moved every tag it had
    # already moved, duplicating the entire block.
    hl = span(html[hd[1]:], '<helmet>', '</helmet>')
    if not hl:
        return html
    hl = (hl[0] + hd[1], hl[1] + hd[1])

    # ---- take them out of <helmet> -------------------------------------
    helmet_body = html[hl[0] + len('<helmet>'):hl[1]]
    kept, moved, in_block = [], [], False
    for line in helmet_body.split('\n'):
        if I18N_START in line:
            in_block = True
        if in_block:
            moved.append(line)
            if I18N_END in line:
                in_block = False
            continue
        (moved if MOVE.match(line) else kept).append(line)

    # ---- complete the card ---------------------------------------------
    head_body = html[hd[0] + len('<head>'):hd[1]]
    existing = head_body + '\n' + '\n'.join(moved)

    def has(pat):
        return re.search(pat, existing) is not None

    # SiteHeader/SiteFooter are imported fragments, not pages: they have a head
    # and a helmet but no title, and nobody ever shares a link to one. Without
    # this they would each pick up a card of their own.
    if not (moved or '<title>' in head_body):
        return html

    extra = []
    img = re.search(r'<meta property="og:image" content="([^"]+)">', existing)
    if img:
        src = img.group(1)
        if src.startswith('/assets/'):
            fixed = SITE + card_for(src)
            moved = [l.replace(src, fixed) if 'og:image' in l else l for l in moved]
            existing = existing.replace(src, fixed)
    else:
        # The blog posts shipped with no card image at all, and they are the
        # pages people actually send each other; each takes the first photograph
        # in its own body. The legal pages have no photograph of their own, so
        # they fall back to the site's — a preview with no image at all is a
        # bare grey box, which reads as a broken link rather than a plain one.
        src = first_body_image(html) or DEFAULT_IMAGE
        extra.append(meta('og:image', SITE + card_for(src)))

    canon = re.search(r'<link rel="canonical" href="([^"]+)">', existing)
    if canon and not has(r'property="og:url"'):
        extra.append(meta('og:url', canon.group(1)))
    if (img or extra) and not has(r'name="twitter:card"'):
        extra.append(meta('twitter:card', 'summary_large_image', attr='name'))

    moved += extra
    if not moved:
        return html

    # ---- put them in <head> --------------------------------------------
    head_lines = head_body.split('\n')
    # Before the scripts, so a crawler that reads only the first few KB of the
    # document has the whole card before it meets any of them.
    at = next((i for i, l in enumerate(head_lines) if l.lstrip().startswith('<script')),
              max(0, len(head_lines) - 1))
    opened = NOTE.split('\n')[0] in head_body
    new_head = head_lines[:at] + ([] if opened else [NOTE]) + moved + head_lines[at:]

    kept_body = '\n'.join(kept)
    kept_body = re.sub(r'\n{3,}', '\n\n', kept_body)
    return (html[:hd[0] + len('<head>')] + '\n'.join(new_head) + html[hd[1]:hl[0] + len('<helmet>')]
            + kept_body + html[hl[1]:])


# --------------------------------------------------------------------------
# the JPEG cards
# --------------------------------------------------------------------------

def wanted_cards(pages):
    """Every /assets/social/… card the transformed pages point at, and its master."""
    want = {}
    for path, html in pages:
        for m in re.finditer(r'content="%s(/assets/social/[^"]+)"' % re.escape(SITE), html):
            card = m.group(1)
            want.setdefault(card, None)
    # Recover each card's master by matching the flattened name back onto a file.
    masters = {}
    for p in (ROOT / 'assets').rglob('*'):
        if p.is_file() and p.suffix.lower() in ('.webp', '.jpg', '.jpeg', '.png'):
            rel = '/' + str(p.relative_to(ROOT)).replace(os.sep, '/')
            if rel.startswith('/assets/social/'):
                continue
            masters[card_for(rel)] = rel
    for card in list(want):
        want[card] = masters.get(card)
    return want


def build_cards(want, check=False):
    made, missing = [], []
    try:
        from PIL import Image
    except ImportError:
        sys.exit('Pillow is required: python3 -m pip install pillow')
    for card, master in sorted(want.items()):
        out = ROOT / card.lstrip('/')
        if master is None:
            missing.append(card)
            continue
        src = ROOT / master.lstrip('/')
        if out.exists() and out.stat().st_mtime >= src.stat().st_mtime:
            continue
        if check:
            made.append(card)
            continue
        out.parent.mkdir(parents=True, exist_ok=True)
        with Image.open(src) as im:
            w, h = im.size
            scale = min(1.0, CARD_MAX / max(w, h))
            im = im.convert('RGB')
            if scale < 1.0:
                im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
            im.save(out, 'JPEG', quality=82, optimize=True, progressive=True)
        made.append(card)
    return made, missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='report drift, write nothing')
    args = ap.parse_args()

    files = sorted(p for p in ROOT.glob('*.html'))
    changed, pages = [], []
    for path in files:
        src = path.read_text(encoding='utf-8')
        out = transform(src, path.name)
        pages.append((path, out))
        if out != src:
            changed.append(path.name)
            if not args.check:
                path.write_text(out, encoding='utf-8')

    made, missing = build_cards(wanted_cards(pages), args.check)

    for n in changed:
        print('  %s: %s' % ('drift' if args.check else 'moved into <head>', n))
    for c in made:
        print('  %s: %s' % ('missing card' if args.check else 'card', c))
    for c in missing:
        print('  NO MASTER for %s — og:image will 404' % c)
    if not changed and not made:
        print('  everything already in step')
    return 1 if (args.check and (changed or made)) or missing else 0


if __name__ == '__main__':
    raise SystemExit(main())
