#!/usr/bin/env python3
"""Give every page a navigation that survives with JavaScript switched off.

The problem
-----------

SiteHeader and SiteFooter are Design Components, pulled in at runtime by
support.js through `<dc-import>`. In the HTML as it leaves the server they are
two empty elements. Everything else on the page — the prose, the headings, the
images — is really there in the source, so this was easy to miss.

The consequence is one number. Fetch the home page the way something that does
not run JavaScript fetches it:

    curl -s -A GPTBot https://paititi-institute.org/ \\
      | grep -o 'href="/[^"]*"' | sort -u | wc -l

Eight. Eight internal links, all of them hand-written into the body of that one
page. The forty links in the header and footer — every initiative, every
program, the Journal, Press, the Spanish tree — exist only after the runtime
has fetched two more documents and re-rendered.

Googlebot renders JavaScript, so Google sees the real header and none of this
affects ordinary search. What does not render: Bingbot's fast path, and most of
the crawlers that matter for AI answers. To those, paititi-institute.org is a
site of eighty orphan pages, each one linking almost nowhere. The sitemap gets
them *found*; it says nothing about which pages belong together, which is the
relationship an answer engine uses when it decides whether the Q'ero page and
the reserve page are part of one body of work or two unrelated documents.

The fix
-------

`<dc-import>` children are passed to the component as props. SiteHeader and
SiteFooter render no children — verified, and it is a property of the templates
rather than of the runtime — so anything written inside the element is
**dropped from the rendered page** and **kept in the source**. That is exactly
the shape of a progressive-enhancement fallback:

  - JavaScript on: the runtime replaces it with the real footer. The visitor,
    and Googlebot, never see it.
  - JavaScript off: `<dc-import>` is an unknown element, its children render as
    ordinary HTML, and the visitor gets a plain list of the same links.
  - No rendering at all: a crawler reads the list out of the source.

This is not cloaking. The links are the ones in the real navigation, they go
where they say they go, and the agent that renders the page gets strictly more
than the agent that does not. Verified 21 Sep 2026 by rendering a probe page in
headless Chrome: the fallback was absent from the DOM and the real footer
present.

Why it is derived and not written out
-------------------------------------

The link list is **parsed out of SiteHeader.dc.html** rather than kept here. A
hand-kept copy of the navigation is a second source of truth for something that
changes whenever Roman adds an initiative, and it would rot in the one way this
repo cannot detect — silently, in the direction of pointing at pages that have
moved. Derived, it cannot disagree with the header, and `--check` says so.

    python3 tools/apply_crawl_nav.py           # insert or refresh
    python3 tools/apply_crawl_nav.py --check   # report drift, write nothing
    python3 tools/apply_crawl_nav.py --remove  # take it back out

Idempotent. Runs anywhere in the pipeline after the page exists; it touches the
body and none of the other tools read that part of the document. It is in
`npm run check`.
"""
import argparse
import pathlib
import re
import sys
from html import escape, unescape

ROOT = pathlib.Path(__file__).resolve().parent.parent

BEGIN = '<!-- BEGIN crawlable nav (generated by tools/apply_crawl_nav.py) -->'
END = '<!-- END crawlable nav -->'
BLOCK_RE = re.compile(re.escape(BEGIN) + r'.*?' + re.escape(END), re.S)

# The element the fallback goes inside. The footer rather than the header: a
# visitor with no JavaScript then meets the page's own content first and the
# link list at the end, which is the order a printed page would use, instead of
# forty links before the headline.
#
# Two names and two shapes. The Spanish tree imports `SiteFooter.es`, and one
# page in each tree carries a hint-size attribute — so a pattern written for the
# bare English tag matches 46 of the 80 pages and silently skips every Spanish
# one. Capturing the attributes and putting them back is what keeps this from
# being a change to half the site.
FOOTER_IMPORT_RE = re.compile(
    r'<dc-import name="(SiteFooter(?:\.es)?)"([^>]*)>(.*?)</dc-import>', re.S)

# Both components, in this order. The header holds the navigation proper; the
# footer is where /contact and the legal pages live and nowhere else, so parsing
# only the header would leave the contact page as unlinked as it is today.
NAV_SRC = {
    'en': ('SiteHeader.dc.html', 'SiteFooter.dc.html'),
    'es': ('SiteHeader.es.dc.html', 'SiteFooter.es.dc.html'),
}

HEADING = {
    'en': 'Paititi Institute',
    'es': 'Instituto Paititi',
}
NOTE = {
    'en': 'Site navigation',
    'es': 'Navegación del sitio',
}


def links_from_header(lang):
    """(href, label) for every internal page the header links to, in order.

    Anchors and duplicates are dropped: `/#impact` and `/initiatives#community-
    health` are positions within a page that is already listed, and repeating
    `/about-us` because it appears in both the desktop and the mobile menu would
    put it in the fallback twice.
    """
    pairs = []
    for name in NAV_SRC[lang]:
        src = (ROOT / name).read_text(encoding='utf-8')
        # Only the rendered part of the component: its <head>/<helmet> carry
        # stylesheet <link>s, not navigation.
        body = src[src.find('</helmet>'):] if '</helmet>' in src else src
        pairs += re.findall(r'<a\b([^>]*\bhref="(/[^"]*)"[^>]*)>(.*?)</a>',
                            body, re.S)

    order, best, toggle = [], {}, {}
    for attrs, href, label in pairs:
        if '#' in href:
            continue
        # The logo link is an icon with an aria-label, not a text link.
        text = re.sub(r'<[^>]+>', '', label)
        text = unescape(re.sub(r'\s+', ' ', text)).strip()
        # A label still holding a {{ … }} hole is a template expression the
        # runtime fills in, not a word. Skipping is right: the alternative is a
        # crawlable link labelled "{{ activePrograms }}".
        if not text or '{{' in text:
            continue
        # The announcement bar leads with an emoji. It belongs on the bar, where
        # it is doing a job; as anchor text in a bare list it is noise in front
        # of the only words a non-rendering agent gets to read.
        text = re.sub(r'^\W+', '', text).strip()
        if not text:
            continue

        # A folder heading and the first entry of its own dropdown point at the
        # same page with different words: /retreats is "Programs" on the toggle
        # and "Retreats" one line below. The toggle is the one carrying
        # data-active. Prefer the other — anchor text is a ranking signal and a
        # description of the destination, and "Retreats" describes /retreats
        # better than the name of the menu it is filed under.
        is_toggle = 'data-active=' in attrs
        if href not in best:
            order.append(href)
            best[href], toggle[href] = text, is_toggle
        elif toggle[href] and not is_toggle:
            best[href], toggle[href] = text, is_toggle
    return [(h, best[h]) for h in order]


def block_for(lang):
    links = links_from_header(lang)
    if not links:
        raise SystemExit('  no links parsed out of %s — refusing to write an '
                         'empty nav' % ', '.join(NAV_SRC[lang]))
    # Re-escaped. The labels were unescaped on the way in so that duplicates
    # compare as text; writing them back raw would put a bare "&" into
    # "Individual Mentorship & Dreamwork" and hand a strict parser an invalid
    # entity in the one element on the page that exists for parsers.
    rows = '\n'.join('    <li><a href="%s">%s</a></li>' % (escape(h, quote=True),
                                                           escape(l))
                     for h, l in links)
    return (
        '%s\n'
        '  <!-- Replaced by the real footer as soon as the DC runtime renders.\n'
        '       Present so that an agent which does not run JavaScript still sees\n'
        '       where this site goes — see tools/apply_crawl_nav.py. -->\n'
        '  <nav class="pt-nav-fallback" aria-label="%s">\n'
        '    <h2>%s</h2>\n'
        '    <ul>\n%s\n    </ul>\n'
        '  </nav>\n'
        '  %s' % (BEGIN, NOTE[lang], HEADING[lang], rows, END)
    )


def lang_of(path):
    return 'es' if '.es.dc.html' in path.name else 'en'


def targets():
    """Pages with a SiteFooter import — which is every real page, and neither
    of the two components themselves."""
    out = []
    for p in sorted(ROOT.glob('*.dc.html')):
        if p.name.startswith(('SiteHeader', 'SiteFooter')):
            continue
        if FOOTER_IMPORT_RE.search(p.read_text(encoding='utf-8')):
            out.append(p)
    return out


def apply(path, src, remove=False):
    def rewrite(m):
        name, attrs, inner = m.group(1), m.group(2), m.group(3)
        inner = BLOCK_RE.sub('', inner).strip()
        if remove:
            body = inner
        else:
            body = (inner + '\n' if inner else '') + block_for(lang_of(path))
        if not body:
            return '<dc-import name="%s"%s></dc-import>' % (name, attrs)
        return '<dc-import name="%s"%s>\n%s\n</dc-import>' % (name, attrs, body)

    return FOOTER_IMPORT_RE.sub(rewrite, src, count=1)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true', help='report drift, write nothing')
    ap.add_argument('--remove', action='store_true', help='take the nav back out')
    args = ap.parse_args()

    changed = []
    for path in targets():
        src = path.read_text(encoding='utf-8')
        new = apply(path, src, remove=args.remove)
        if new != src:
            changed.append(path.name)
            if not args.check:
                path.write_text(new, encoding='utf-8')

    verb = 'drift' if args.check else ('removed' if args.remove else 'wrote')
    for name in changed:
        print('  %s: %s' % (verb, name))
    if not changed:
        print('  everything already in step')
    else:
        n_en = len(links_from_header('en'))
        print('  %d page(s), %d links' % (len(changed), n_en))
    return 1 if (args.check and changed) else 0


if __name__ == '__main__':
    sys.exit(main())
