#!/usr/bin/env python3
"""Keep the English<->Spanish annotations in step with tools/i18n_pairs.json.

Three things have to agree for the two trees to be one bilingual site, and all
three are derived from the pair table rather than typed out per page:

  1. a self-referencing rel="canonical" plus rel="alternate" hreflang in each
     page's <helmet>. Google ignores the whole hreflang annotation unless *both*
     pages name *both* URLs, so they are written as a block into the English
     page and its .es counterpart alike.
  2. the `sister` prop on the <dc-import> of SiteHeader / SiteHeader.es, which
     is what the EN/ES switcher in the bar actually links to.
  3. sitemap.xml, where each <url> repeats the same pair as <xhtml:link>.

Idempotent: it replaces its own previous block (marked by the comment below)
rather than appending a second one. Run it after editing the pair table:

    python3 tools/apply_hreflang.py            # rewrite pages + sitemap
    python3 tools/apply_hreflang.py --check    # report drift, change nothing
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TABLE = ROOT / "tools" / "i18n_pairs.json"
MARK = "<!-- i18n:hreflang (generated by tools/apply_hreflang.py) -->"
END = "<!-- /i18n:hreflang -->"

# Anchored on og:site_name, which every page in this repo carries exactly once
# and which sits in the block of social/meta tags the hreflang links belong with.
ANCHOR = '<meta property="og:site_name" content="Paititi Institute">'


def es_file(name: str) -> str:
    return name.replace(".dc.html", ".es.dc.html")


def block(origin: str, self_url: str, en: str, es: str | None = None) -> str:
    # Every page names itself as canonical, so a crawler that arrives via
    # ?utm_source=… or a stray query string files it under the clean URL
    # instead of indexing the variant as a separate page. The alternates only
    # follow when both halves of the pair exist.
    lines = [MARK, f'<link rel="canonical" href="{origin}{self_url}">']
    if es is not None:
        lines += [
            f'<link rel="alternate" hreflang="en" href="{origin}{en}">',
            f'<link rel="alternate" hreflang="es" href="{origin}{es}">',
            # x-default is English: the older tree, the better-linked one, and
            # the right landing place for a reader whose language we do not
            # publish.
            f'<link rel="alternate" hreflang="x-default" href="{origin}{en}">',
        ]
    lines.append(END)
    return "\n".join(lines)


def set_block(html: str, new: str) -> str:
    """Insert or replace the generated hreflang block."""
    existing = re.compile(re.escape(MARK) + r".*?" + re.escape(END), re.S)
    if existing.search(html):
        return existing.sub(lambda _: new, html, count=1)
    # Drop any hand-written alternates first, so a page edited before this
    # script existed does not end up declaring each pair twice.
    html = re.sub(r'^[ \t]*<link rel="alternate" hreflang="[^"]*"[^>]*>\n', "", html, flags=re.M)
    if ANCHOR not in html:
        raise SystemExit(f"no og:site_name anchor to place hreflang after")
    return html.replace(ANCHOR, ANCHOR + "\n" + new, 1)


def set_lang(html: str, lang: str) -> str:
    return re.sub(r"<html(?:\s+lang=\"[^\"]*\")?>", f'<html lang="{lang}">', html, count=1)


def set_sister(html: str, component: str, sister: str) -> str:
    """Point this page's header import at its counterpart in the other tree."""
    tag = re.compile(r'<dc-import name="' + re.escape(component) + r'"[^>]*>')
    m = tag.search(html)
    if not m:
        raise SystemExit(f'no <dc-import name="{component}"> to set sister on')
    # Drop any sister already on the tag before adding one back, wherever in the
    # attribute order it sits — otherwise a hand-written one earlier in the tag
    # survives and the element ends up carrying the attribute twice.
    inner = re.sub(r'\s+sister="[^"]*"', "", m.group(0))
    return html[: m.start()] + inner[:-1].rstrip() + f' sister="{sister}">' + html[m.end():]


def sitemap(origin: str, pairs, english_only=()) -> str:
    rows = []
    for p in pairs:
        for loc in (origin + p["en"], origin + p["es"]):
            rows.append(
                "  <url>\n"
                f"    <loc>{loc}</loc>\n"
                f'    <xhtml:link rel="alternate" hreflang="en" href="{origin}{p["en"]}"/>\n'
                f'    <xhtml:link rel="alternate" hreflang="es" href="{origin}{p["es"]}"/>\n'
                f'    <xhtml:link rel="alternate" hreflang="x-default" href="{origin}{p["en"]}"/>\n'
                "  </url>"
            )
    # Pages with no Spanish counterpart still belong in the sitemap. They get a
    # plain <url> with no hreflang, because there is no alternate to declare.
    for p in english_only:
        rows.append("  <url>\n" f"    <loc>{origin}{p['en']}</loc>\n" "  </url>")
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- Generated by tools/apply_hreflang.py from tools/i18n_pairs.json.\n"
        "     Do not edit by hand: add the page to the pair table and re-run. -->\n"
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
        + "\n".join(rows)
        + "\n</urlset>\n"
    )


def main() -> int:
    check = "--check" in sys.argv
    cfg = json.loads(TABLE.read_text(encoding="utf-8"))
    origin, pairs = cfg["origin"], cfg["pairs"]
    drift, missing = [], []

    for p in pairs:
        # Both halves are annotated only once both halves exist. Announcing a
        # Spanish URL that is not built yet would point hreflang, the sitemap
        # and the header's ES link at a 404 — worse than saying nothing, since
        # a 404 on a declared alternate invalidates the pair for that page.
        if not (ROOT / es_file(p["file"])).exists():
            missing.append(es_file(p["file"]))
            # Retract an annotation written by an earlier run, so removing or
            # renaming a Spanish page cleans up its English half too. The
            # canonical stays: it is about this page, not the pair.
            path = ROOT / p["file"]
            if path.exists():
                before = path.read_text(encoding="utf-8")
                # lang is set either way: every page should declare the language
                # it is written in, whether or not it has a counterpart yet.
                after = set_block(set_lang(before, "en"), block(origin, p["en"], p["en"]))
                after = re.sub(r'\s+sister="[^"]*"', "", after, count=1)
                if after != before:
                    drift.append(p["file"] + " (retracted)")
                    if not check:
                        path.write_text(after, encoding="utf-8")
            continue
        for name, lang, component, self_url, sister in (
            (p["file"], "en", "SiteHeader", p["en"], p["es"]),
            (es_file(p["file"]), "es", "SiteHeader.es", p["es"], p["en"]),
        ):
            path = ROOT / name
            if not path.exists():
                missing.append(name)
                continue
            blk = block(origin, self_url, p["en"], p["es"])
            before = path.read_text(encoding="utf-8")
            after = set_sister(set_block(set_lang(before, lang), blk), component, sister)
            if after != before:
                drift.append(name)
                if not check:
                    path.write_text(after, encoding="utf-8")

    # Pages with no Spanish counterpart by design still get lang + canonical.
    for p in cfg.get("english_only", []):
        path = ROOT / p["file"]
        if not path.exists():
            continue
        before = path.read_text(encoding="utf-8")
        after = set_block(set_lang(before, "en"), block(origin, p["en"], p["en"]))
        if after != before:
            drift.append(p["file"])
            if not check:
                path.write_text(after, encoding="utf-8")

    sm = ROOT / "sitemap.xml"
    english_only = [p for p in cfg.get("english_only", []) if (ROOT / p["file"]).exists()]
    want = sitemap(origin, [p for p in pairs if (ROOT / es_file(p["file"])).exists()], english_only)
    if sm.read_text(encoding="utf-8") != want:
        drift.append("sitemap.xml")
        if not check:
            sm.write_text(want, encoding="utf-8")

    for n in missing:
        print(f"  not built yet: {n}")
    for n in drift:
        print(f"  {'drift' if check else 'updated'}: {n}")
    if not drift:
        print("  everything already in step")
    return 1 if (check and drift) else 0


if __name__ == "__main__":
    raise SystemExit(main())
