#!/usr/bin/env python3
"""Give every retreat its own page, and its own shareable link.

Until now the only URL for a program was /retreats — the listing. The Retreat
Guru widget's cards link to "#/event/<id>/<slug>", a hash route *inside* the
iframe, so clicking one changed nothing in the address bar: the same
paititi-institute.org/retreats went to everybody, whichever retreat you meant.

This generates one page per program at

    /retreats/<slug>

from Retreat Guru's own program feed, so a link to a single retreat can be
pasted into an email, a WhatsApp message or an ad, and arrives with that
retreat's title, photo and dates in the preview card.

    python3 tools/gen_retreats.py             # fetch, regenerate, rewire
    python3 tools/gen_retreats.py --offline   # rebuild from data/retreats.json
    python3 tools/gen_retreats.py --check     # report drift, change nothing

Re-run it whenever a program is added, retired or edited on Retreat Guru — the
dates, prices and description here are a snapshot, and only a re-run refreshes
them. (The volatile lines — dates, contribution, whether registration is open —
also refresh themselves in the reader's browser from the same public feed, so a
stale page corrects itself rather than misleading anyone; see PAGE_JS below.)

What it touches, all of it idempotent:

    Retreat-<slug>.dc.html      one per program (removed when a program goes)
    data/retreats.json          the snapshot --offline rebuilds from
    assets/retreats/rg/         each program's photo, mirrored + a size ladder
    _redirects                  the clean URLs, inside a marked block
    tools/i18n_pairs.json       the `english_only` rows, so the sitemap and the
                                canonical tags come from the one place that
                                already owns them (run apply_hreflang.py after)
    Retreats*.dc.html           the `pages=` list the widget links against
    retreatguru-deeplink.js     the ?program=<id> map

Programs not on Retreat Guru — the Himalayan pilgrimage, which the Karuna
Project runs and registers — are listed in data/retreats-extra.json and render
through the same template.
"""
import argparse
import html as htmllib
import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = 'https://paititi-institute.org'
RG = 'https://paititi-institute.secure.retreat.guru'
FEED = RG + '/wp-json/events/'

SNAPSHOT = ROOT / 'data' / 'retreats.json'
EXTRA = ROOT / 'data' / 'retreats-extra.json'
PAIRS = ROOT / 'tools' / 'i18n_pairs.json'
ASSET_DIR = ROOT / 'assets' / 'retreats' / 'rg'

# Categories that mean "you travel to this one". The online courses carry
# `breathwork` and `online-resources` and belong on /online-courses instead.
# Kept deliberately in step with the `cat=` on the /retreats widget iframe.
IN_PERSON = {
    'events', 'public-talks', 'retreat', 'breathwork-retreat',
    'transformation-retreats', 'embodying-true-nature-retreats',
    'peru-programs', 'us-mexico-programs',
}

LADDER = [320, 480, 640, 800, 1080, 1280, 1600, 2000]

REDIR_BEGIN = '# BEGIN retreat pages (generated by tools/gen_retreats.py)'
REDIR_END = '# END retreat pages'
DEST_BEGIN = '  // BEGIN destinations (generated by tools/gen_retreats.py)'
DEST_END = '  // END destinations'


# --------------------------------------------------------------------------
# fetching
# --------------------------------------------------------------------------

def fetch(url):
    """curl, not urllib: this machine's python has no SSL root certificates."""
    out = subprocess.run(['curl', '-fsSL', url], capture_output=True)
    if out.returncode != 0:
        raise SystemExit('  fetch failed: %s\n  %s' % (url, out.stderr.decode()[:200]))
    return out.stdout


def fetch_json(url):
    return json.loads(fetch(url).decode('utf-8'))


def pull():
    """The listing, then each program in full. Both endpoints are server-rendered
    and open — Retreat Guru's /api/v1 needs a login, this does not."""
    listing = fetch_json(FEED + '?ver=react')
    programs = []
    for item in listing:
        cats = {c['slug'] for c in item.get('categories', [])}
        if not (cats & IN_PERSON):
            continue
        full = fetch_json('%s%s' % (FEED, item['ID']))
        programs.append(full)
        print('    pulled %s (%s)' % (full['slug'], full['ID']))
    programs.sort(key=lambda p: p.get('start') or 0)
    return programs


# --------------------------------------------------------------------------
# text
# --------------------------------------------------------------------------

def text(s):
    """Retreat Guru double-escapes some titles ("Redding, Ca &#8211; ...")."""
    return htmllib.unescape(htmllib.unescape(s or '')).strip()


def esc(s):
    return htmllib.escape(text(s), quote=True)


def plain(s, limit=None):
    s = re.sub(r'<[^>]+>', ' ', s or '')
    s = re.sub(r'\s+', ' ', htmllib.unescape(s)).strip()
    if limit and len(s) > limit:
        s = s[:limit].rsplit(' ', 1)[0].rstrip(' ,;:.—–-') + '…'
    return s


# Attributes worth keeping on the program body. Everything else — WordPress and
# ChatGPT both leave a trail of data-start / data-section-id / class="isSelected"
# on every paragraph — is noise that would also have to be styled around.
KEEP_ATTRS = {'href', 'src', 'alt', 'title', 'width', 'height', 'colspan', 'rowspan'}
BLOCKED_TAGS = re.compile(r'<(script|style|iframe|form|input|noscript)\b.*?</\1>|<(script|style|iframe|form|input|noscript)\b[^>]*/?>', re.S | re.I)
TAG = re.compile(r'<(/?)([a-zA-Z][a-zA-Z0-9]*)((?:\s+[^\s=>]+(?:\s*=\s*(?:"[^"]*"|\'[^\']*\'|[^\s>]+))?)*)\s*(/?)>')
ATTR = re.compile(r'([^\s=]+)\s*=\s*"([^"]*)"|([^\s=]+)\s*=\s*\'([^\']*)\'')


def clean_body(raw):
    """Retreat Guru's rich text, reduced to what this site can style.

    Nothing here is rewritten for meaning — tags are dropped, attributes are
    dropped, headings are demoted one level so the page keeps a single h1, and
    that is all."""
    if not raw:
        return ''
    body = BLOCKED_TAGS.sub('', raw)

    def one(m):
        close, name, attrs, self_close = m.group(1), m.group(2).lower(), m.group(3), m.group(4)
        # h1 in the body would be a second document title: the page already has
        # one, and it is the same words. Demote the whole heading run with it so
        # the outline stays ordered.
        name = {'h1': 'h2', 'h2': 'h3', 'h3': 'h4', 'h4': 'h5'}.get(name, name)
        if close:
            return '</%s>' % name
        kept = []
        for a in ATTR.finditer(attrs):
            key = (a.group(1) or a.group(3)).lower()
            val = a.group(2) if a.group(2) is not None else a.group(4)
            if key in KEEP_ATTRS:
                kept.append('%s="%s"' % (key, htmllib.escape(val, quote=True)))
        if name == 'a':
            kept += ['target="_blank"', 'rel="noopener"']
        if name == 'img':
            kept.append('loading="lazy"')
        return '<%s%s%s>' % (name, (' ' + ' '.join(kept)) if kept else '', ' /' if self_close else '')

    body = TAG.sub(one, body)
    # Empty paragraphs survive the attribute strip as <p></p>; the runtime drops
    # whitespace-only ones anyway, so take them out here where it is visible.
    body = re.sub(r'<p>(?:\s|&nbsp;)*</p>', '', body)
    # The Design Component runtime interpolates {{ ... }}. A program description
    # containing braces would be compiled as an expression and render as nothing.
    body = body.replace('{{', '&#123;&#123;').replace('}}', '&#125;&#125;')
    return body.strip()


# --------------------------------------------------------------------------
# images
# --------------------------------------------------------------------------

def mirror_photo(url, slug, check=False):
    """Bring the program photo onto our own domain.

    og:image has to be an absolute URL on a host that will still serve it when
    somebody pastes the link into WhatsApp a month from now — and the preview
    card is most of the reason these pages exist."""
    if not url:
        return None, ''
    # An entry in data/retreats-extra.json names a photo we already host — the
    # Himalayan pilgrimage's, mirrored for /retreats long before this script.
    # Use it where it lies; assets/ is sync_assets.py's to own, not ours.
    if url.startswith('/assets/'):
        master = ROOT / url.lstrip('/')
        if not master.exists():
            print('    missing photo %s' % url)
            return None, ''
        return url, ''
    ext = os.path.splitext(url.split('?')[0])[1].lower() or '.jpg'
    if ext not in ('.jpg', '.jpeg', '.png', '.webp'):
        ext = '.jpg'
    master = ASSET_DIR / (slug + ext)
    rel = '/' + str(master.relative_to(ROOT)).replace(os.sep, '/')
    if not master.exists():
        if check:
            return rel, ''
        ASSET_DIR.mkdir(parents=True, exist_ok=True)
        master.write_bytes(fetch(url))
        print('    photo %s' % rel)
    try:
        from PIL import Image
    except ImportError:
        return rel, ''
    with Image.open(master) as im:
        nat_w, nat_h = im.size
        entries = []
        for w in [w for w in LADDER if w < nat_w]:
            out = ROOT / 'assets' / 'r' / 'retreats' / 'rg' / ('%s-%dw.webp' % (slug, w))
            if not out.exists() and not check:
                out.parent.mkdir(parents=True, exist_ok=True)
                copy = im.convert('RGBA' if 'A' in im.getbands() else 'RGB')
                h = max(1, round(nat_h * w / nat_w))
                copy.resize((w, h), Image.LANCZOS).save(out, 'WEBP', quality=82, method=6)
            if out.exists():
                entries.append('/%s %dw' % (str(out.relative_to(ROOT)).replace(os.sep, '/'), w))
    entries.append('%s %dw' % (rel, nat_w))
    return rel, ', '.join(entries)


def social_card(local, slug, check=False):
    """The image a link preview actually shows, as its own file.

    Not the master: one of these is a 2.2MB PNG, and og:image is fetched by
    every chat app that ever sees the link. Not a WebP either — the size ladder
    is WebP and the page uses it, but LinkedIn and older Mail/Messages builds
    still show nothing for a WebP card. So: JPEG, longest side 1200, no crop.
    Cropping to Facebook's 1.91:1 would take the top off a square portrait, and
    every scraper crops to its own frame anyway."""
    if not local:
        return None, 0, 0
    master = ROOT / local.lstrip('/')
    if not master.exists():
        return None, 0, 0
    out = ASSET_DIR / (slug + '-card.jpg')
    rel = '/' + str(out.relative_to(ROOT)).replace(os.sep, '/')
    try:
        from PIL import Image
    except ImportError:
        return local, 0, 0
    with Image.open(master) as im:
        w, h = im.size
        scale = min(1.0, 1200 / max(w, h))
        size = (max(1, round(w * scale)), max(1, round(h * scale)))
        if not out.exists() and not check:
            out.parent.mkdir(parents=True, exist_ok=True)
            copy = im.convert('RGB')
            if scale < 1.0:
                copy = copy.resize(size, Image.LANCZOS)
            copy.save(out, 'JPEG', quality=82, optimize=True, progressive=True)
            print('    card %s (%dx%d)' % (rel, *size))
    return (rel if out.exists() else local), size[0], size[1]


# --------------------------------------------------------------------------
# the page
# --------------------------------------------------------------------------

# Dates, contribution and whether registration is open are the three facts that
# go stale between runs of this script, and the three it is worst to be wrong
# about. They come back from the same public feed the widget uses — CORS is open
# on it and _headers already allows the origin in connect-src — so the page
# corrects itself in the reader's browser. Everything else stays static, which
# is what the crawler and the link-preview scraper read.
PAGE_JS = """
  (function () {
    var id = %(id)s;
    if (!id) return;
    fetch('%(rg)s/wp-json/events/' + id, { credentials: 'omit' })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (p) {
        if (!p) return;
        var set = function (sel, val) {
          var el = document.querySelector(sel);
          if (el && val && el.textContent.trim() !== String(val).trim()) el.textContent = val;
        };
        set('[data-live="date"]', p.date);
        set('[data-live="price"]', (p.prices || '').replace(/&ndash;/g, '–').replace(/<[^>]+>/g, ''));
        var cta = document.querySelectorAll('[data-live="register"]');
        for (var i = 0; i < cta.length; i++) {
          if (p.registration_link) cta[i].href = p.registration_link;
          if (p.registration_status && p.registration_status !== 'open') {
            cta[i].textContent = p.registration_status === 'wait-list'
              ? 'Join the wait list' : 'Registration closed';
          }
        }
      })
      .catch(function () { /* the static values below stand */ });
  })();
"""

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="/favicon.ico" sizes="any">
<!-- The title and the social card sit in the real <head>, not in <helmet>
     below, and that is deliberate. <helmet> is appended to the head by
     support.js *at runtime*; the crawlers that build a link preview — WhatsApp,
     Messages, Slack, Facebook, LinkedIn — read the HTML as it arrives and run
     no JavaScript. A page whose og:title only exists after render pastes into a
     chat as a bare URL, which is precisely what these pages exist to avoid.
     Every other page on the site still declares its meta inside <helmet>; see
     the note in docs/seo.md. -->
<title>{title} | Paititi Institute</title>
<meta name="description" content="{description}">
<meta property="og:title" content="{title} | Paititi Institute">
<meta property="og:description" content="{description}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="Paititi Institute">
<!-- i18n:hreflang (generated by tools/apply_hreflang.py) -->
<link rel="canonical" href="{site}{url}">
<!-- /i18n:hreflang -->
<meta property="og:image" content="{site}{card}">
<meta property="og:image:width" content="{card_w}">
<meta property="og:image:height" content="{card_h}">
<meta property="og:image:alt" content="{photo_alt}">
<meta property="og:url" content="{site}{url}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="{site}{card}">
<script src="/support.js"></script>
<script src="/anchor-scroll.js" defer></script>
</head>
<body>
<x-dc>
<helmet>
<meta name="theme-color" content="#2A1736">
<link rel="icon" href="/assets/brand/favicon.png" type="image/png">
<link rel="apple-touch-icon" href="/assets/brand/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="stylesheet" href="/_ds/meristem-design-system/tokens/fonts.css">
<link rel="stylesheet" href="/_ds/meristem-design-system/tokens/colors.css">
<link rel="stylesheet" href="/_ds/meristem-design-system/tokens/typography.css">
<link rel="stylesheet" href="/_ds/meristem-design-system/tokens/spacing.css">
<link rel="stylesheet" href="/_ds/meristem-design-system/tokens/effects.css">
<link rel="stylesheet" href="/_ds/meristem-design-system/styles.css">
<link rel="stylesheet" href="/paititi.css">
<script src="/_ds/meristem-design-system/_ds_bundle.js"></script>
<script type="application/ld+json">{jsonld}</script>
<style>
  /* One program, in flow — like every page added after the replica, this
     transcribes no Squarespace grid, so it needs no measured rows. Rules that
     set colour, margin or size on a p or h* carry `.pt-page main`: the base
     scale in paititi.css is written that way and a bare class loses to it. */
  /* The hero has to work for whatever Retreat Guru holds as the program's
     photograph, and that is not always a photograph: one current program is
     illustrated with word art of its own title. Laying a headline over that
     gives two titles fighting each other. So the program's image appears twice
     and never underneath the type — blurred right down as the ground, and
     crisp in a frame beside the words, where a poster stays readable as a
     poster and a photograph stays a photograph. */
  .rp-hero{{--pt-hero-h:auto;--pt-bg:#210416;--pt-scrim:rgba(33,4,22,.62);--pt-hero-ink:#fff;
    min-height:min(72vh,660px);display:grid;align-items:end;text-align:left}}
  .rp-hero .pt-sec-bg > img{{filter:blur(34px) saturate(1.15) brightness(.62);transform:scale(1.15)}}
  .rp-hero-in{{max-width:1324px;margin:0 auto;padding:190px 58px 72px;width:100%;
    display:grid;grid-template-columns:minmax(0,1.45fr) minmax(0,1fr);gap:56px;align-items:center}}
  .pt-page main .rp-back{{display:inline-block;font-size:14.272px;letter-spacing:.06em;
    text-transform:uppercase;color:#fff;text-decoration:none;opacity:.82;margin-bottom:22px}}
  .rp-back:hover{{opacity:1;text-decoration:underline}}
  .pt-page main .rp-kicker{{display:block;font-size:13px;font-weight:700;letter-spacing:.18em;
    text-transform:uppercase;line-height:1.4;color:#E4D6EE;margin:0 0 14px}}
  .pt-page main .rp-hero h1{{color:#fff;margin:0}}
  .pt-page main .rp-hero .rp-teachers{{color:#fff;font-size:19.2px;margin:18px 0 0;opacity:.92}}
  /* The square is on the figure, not the image: an <img> carries width and
     height attributes (they reserve the box and keep the page from jumping),
     and a presentational height beats aspect-ratio — leave it to the image and
     a 1667px-tall photo is what you get. */
  .rp-hero-art{{margin:0;aspect-ratio:1;border-radius:48px 0;overflow:hidden;
    box-shadow:0 24px 60px rgba(0,0,0,.42)}}
  .rp-hero-art img{{display:block;width:100%;height:100%;object-fit:cover}}

  /* The facts somebody scans for before they read a word: when, where, who,
     how much. Kept out of the prose so they survive being skimmed. */
  .rp-facts{{--pt-bg:#F1EAF6;padding:44px 0 48px}}
  .rp-in{{max-width:1324px;margin:0 auto;padding:0 58px}}
  .rp-facts-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:28px 40px}}
  .pt-page main .rp-facts dt{{font-size:13px;font-weight:700;letter-spacing:.14em;
    text-transform:uppercase;color:#6B5378;margin:0 0 6px}}
  .pt-page main .rp-facts dd{{margin:0;font-size:17.6px;line-height:1.6;color:#210416}}
  .rp-facts .pt-btn{{margin-top:32px;min-height:56px}}

  .rp-body{{--pt-bg:#fff;padding:76px 0 84px}}
  .rp-body-in{{max-width:820px;margin:0 auto;padding:0 24px}}
  /* Retreat Guru's rich text, reduced to bare tags by the generator, so the
     rhythm can be set here rather than fought with. */
  .pt-page main .rp-body-in > *{{margin:0 0 18px}}
  .pt-page main .rp-body-in > h2,
  .pt-page main .rp-body-in > h3,
  .pt-page main .rp-body-in > h4,
  .pt-page main .rp-body-in > h5{{margin:38px 0 16px;color:#584364}}
  /* Retreat Guru's descriptions nest three or four heading levels, and after
     the demotion that pushes the section headings down to h4/h5, where the base
     scale is 19.2px — the same size as the paragraph under it, so the structure
     of a long program page disappears. Give the lower two levels their own
     steps back. */
  .pt-page main .rp-body-in > h4{{font-size:24px;margin-top:42px}}
  .pt-page main .rp-body-in > h5{{font-size:19.2px;font-weight:700;margin-top:34px}}
  .pt-page main .rp-body-in > *:first-child{{margin-top:0}}
  .pt-page main .rp-body-in > *:last-child{{margin-bottom:0}}
  .rp-body-in ul,.rp-body-in ol{{margin:0 0 18px;padding-left:32px}}
  .pt-page main .rp-body-in li{{margin-bottom:10px;font-size:17.6px;line-height:1.8}}
  .rp-body-in img{{max-width:100%;height:auto;display:block;margin:28px auto;border-radius:24px 0}}
  .rp-body-in a{{color:#584364;text-decoration:underline;text-underline-offset:3px}}
  .rp-body-in blockquote{{margin:28px 0;padding-left:24px;border-left:3px solid #C9B6D8;
    font-style:italic}}
  .rp-body-in table{{width:100%;border-collapse:collapse}}
  .rp-body-in td,.rp-body-in th{{border:1px solid #E0D4E9;padding:10px 12px;text-align:left}}

  .rp-video{{max-width:820px;margin:52px auto 0;padding:0 24px}}
  .rp-video .pt-embed{{border-radius:32px 0;overflow:hidden;background:#2A1736}}

  .rp-gallery{{--pt-bg:#fff;padding:0 0 84px}}
  /* Three across, not auto-fit: the galleries hold six shots, and auto-fit
     packs them 4 + 2 with a ragged second row. */
  .rp-gallery-strip{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}}
  .rp-gallery-strip img{{width:100%;height:260px;object-fit:cover;display:block;border-radius:24px 0}}

  /* The whole point of the page: one button, on our domain, that a person who
     was sent the link can actually act on. */
  .rp-cta{{--pt-bg:#584364;color:#fff;padding:72px 0 78px;text-align:center}}
  .pt-page main .rp-cta h2,.pt-page main .rp-cta p{{color:#fff}}
  .pt-page main .rp-cta p{{max-width:620px;margin:16px auto 0;font-size:19.2px}}
  .rp-cta .pt-btn{{margin-top:34px;min-height:60px;padding:0 42px}}

  .rp-more{{--pt-bg:#F1EAF6;padding:64px 0 72px}}
  .pt-page main .rp-more h2{{color:#584364;font-size:28.8px;margin:0 0 28px}}
  .rp-cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:24px}}
  .rp-card{{display:block;background:#fff;border-radius:32px 0;overflow:hidden;text-decoration:none;
    box-shadow:0 10px 30px rgba(33,4,22,.08);transition:transform .18s ease,box-shadow .18s ease}}
  .rp-card:hover{{transform:translateY(-3px);box-shadow:0 16px 38px rgba(33,4,22,.14)}}
  .rp-card img{{width:100%;height:180px;object-fit:cover;display:block}}
  .rp-card-body{{padding:22px 24px 26px}}
  .pt-page main .rp-card h3{{font-size:21px;line-height:1.3;color:#210416;margin:0 0 8px;
    font-family:var(--font-display);font-weight:400;letter-spacing:normal}}
  .pt-page main .rp-card p{{font-size:14.272px;color:#6B5378;margin:0}}

  .rp-footnote{{--pt-bg:#fff;padding:0 0 56px}}
  .pt-page main .rp-footnote p{{font-size:14.272px;color:#6B5378;text-align:center;margin:0}}
  .rp-footnote a{{color:#584364}}

  @media (max-width:1180px){{
    /* Below the breakpoint paititi.css gives .pt-hero its own header clearance
       (--pt-header-h-live + 32px). Keeping a second top padding here on top of
       it left a phone screen half full of empty plum before the title. */
    .rp-hero-in{{padding:0 24px;grid-template-columns:1fr;gap:34px}}
    /* Copy first on a phone: the headline is what tells you which retreat this
       is, and the reader arrived here from a link that promised exactly that. */
    .rp-hero-art{{order:2;max-width:420px}}
    .pt-page main .rp-hero h1{{font-size:40px}}
    .rp-in{{padding:0 24px}}
    .rp-body{{padding:56px 0 64px}}
    .rp-cta{{padding:56px 0 62px}}
    .rp-more{{padding:52px 0 58px}}
    .rp-gallery-strip{{grid-template-columns:repeat(2,minmax(0,1fr))}}
    .rp-gallery-strip img{{height:200px}}
  }}
  @media (max-width:640px){{
    .rp-hero-in{{padding:0 20px}}
    .pt-page main .rp-hero h1{{font-size:32px}}
    .rp-facts-grid{{gap:22px}}
  }}
</style>
</helmet>
<div class="pt-page">
<dc-import name="SiteHeader" active="programs" hint-size="100%,209px"></dc-import>
<main>

  <!-- ===== Hero ===== -->
  <section class="pt-sec pt-sec-flat pt-hero rp-hero">
    <div class="pt-sec-bg">
      <!-- sizes="200px" on purpose: this copy is blurred to 34px, so the
           narrowest rung of the ladder is all it can possibly show. -->
      <img src="{photo}"{srcset} sizes="200px" width="{photo_w}" height="{photo_h}"
           decoding="async" alt="" loading="eager" aria-hidden="true">
    </div>
    <div class="rp-hero-in">
      <div>
        <a class="rp-back" href="/retreats">&larr; All retreats &amp; events</a>
        <span class="rp-kicker">{kicker}</span>
        <h1>{title}</h1>
        {teachers_html}
      </div>
      <figure class="rp-hero-art">
        <img src="{photo}"{srcset} sizes="(max-width:1180px) 78vw, 420px"
             width="{photo_w}" height="{photo_h}"
             decoding="async" alt="{photo_alt}" loading="eager" fetchpriority="high">
      </figure>
    </div>
  </section>

  <!-- ===== The facts, before the prose ===== -->
  <section class="pt-sec rp-facts">
    <div class="pt-sec-bg"></div>
    <div class="rp-in">
      <dl class="rp-facts-grid">
{facts}
      </dl>
      {facts_cta}
    </div>
  </section>

  <!-- ===== The program, as Retreat Guru describes it =====
       The video, where there is one, sits after the description rather than
       before it: it is whatever film is attached to the program in Retreat
       Guru, often the Institute's own, and it is context for the program
       rather than the thing the reader followed the link to read. Both live in
       one section — two adjacent .pt-sec blocks would draw a wave edge between
       them, mid-page, for no reason. -->
  <section class="pt-sec rp-body">
    <div class="pt-sec-bg"></div>
    <div class="rp-body-in pt-prose">
{body}
    </div>
{video}
  </section>
{gallery}
  <!-- ===== Register ===== -->
  <section class="pt-sec rp-cta" id="register">
    <div class="pt-sec-bg"></div>
    <div class="rp-in">
      <h2>{cta_heading}</h2>
      <p>{cta_note}</p>
      <a class="pt-btn pt-btn-light" href="{register}" target="_blank" rel="noopener"{live_reg}>{cta_label}</a>
    </div>
  </section>
{more}
  <section class="pt-sec rp-footnote">
    <div class="pt-sec-bg"></div>
    <div class="rp-in">
      <p>Retreat fees sustain the Institute&rsquo;s conservation, Indigenous education and community
      work &mdash; see <a href="/initiatives">where your participation goes</a>.</p>
    </div>
  </section>

</main>
<dc-import name="SiteFooter"></dc-import>
</div>
</x-dc>
<script>{page_js}</script>
</body>
</html>
"""


def fact(term, value):
    return ('        <div><dt>%s</dt><dd%s>%s</dd></div>'
            % (term[0], (' data-live="%s"' % term[1]) if len(term) > 1 else '', value))


def render(p, others):
    slug = p['slug']
    title = text(p['title'])
    url = '/retreats/' + slug
    photo = p.get('_photo') or '/assets/retreats/coco-ceremony.webp'
    srcset = p.get('_srcset') or ''
    desc = plain(p.get('excerpt') or p.get('text') or '', 300)

    facts = []
    if p.get('date'):
        facts.append(fact(('Dates', 'date'), esc(p['date'])))
    where = text(p.get('location') or p.get('address') or '')
    if where:
        facts.append(fact(('Where',), esc(where)))
    if p.get('teacher_list'):
        facts.append(fact(('Guided by',), esc(re.sub(r'^Facilitated by\s+', '', text(p['teacher_list'])))))
    if p.get('prices'):
        facts.append(fact(('Contribution', 'price'), esc(p['prices'])))

    kicker_bits = [c['name'] for c in p.get('categories', []) if c['slug'] in
                   ('retreat', 'breathwork-retreat', 'events', 'public-talks',
                    'embodying-true-nature-retreats')]
    kicker = text(kicker_bits[0]) if kicker_bits else 'Program'

    teachers_html = ''
    if p.get('teacher_list'):
        teachers_html = '<p class="rp-teachers">%s</p>' % esc(p['teacher_list'])

    register = p.get('registration_link') or (RG + '/program/%s/' % slug)
    closed = p.get('registration_status') and p['registration_status'] != 'open'
    cta_label = 'Registration closed' if closed else text(p.get('_cta') or 'Apply &amp; register')
    cta_label = htmllib.escape(htmllib.unescape(cta_label))

    facts_cta = ('<a class="pt-btn" href="#register">%s</a>'
                 % ('Details &amp; registration' if not closed else 'Program details'))

    video = ''
    vid = ((p.get('marketplace') or {}).get('video') or {}).get('text') or ''
    m = re.search(r'(?:youtu\.be/|youtube\.com/(?:watch\?v=|embed/))([\w-]{6,})', vid)
    if m:
        video = ('    <div class="rp-video"><div class="pt-embed">'
                 '<iframe src="https://www.youtube-nocookie.com/embed/%s" title="%s" '
                 'allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; '
                 'picture-in-picture" allowfullscreen loading="lazy"></iframe></div></div>\n'
                 % (m.group(1), esc(title)))

    gallery = ''
    shots = [g for g in (p.get('gallery_images') or []) if g][:6]
    if shots:
        imgs = '\n'.join(
            '        <img src="%s" alt="" loading="lazy" decoding="async">' % htmllib.escape(g, quote=True)
            for g in shots)
        gallery = ('\n  <section class="pt-sec rp-gallery">\n'
                   '    <div class="pt-sec-bg"></div>\n'
                   '    <div class="rp-in">\n      <div class="rp-gallery-strip">\n%s\n      </div>\n'
                   '    </div>\n  </section>\n' % imgs)

    more = ''
    siblings = [o for o in others if o['slug'] != slug][:3]
    if siblings:
        cards = []
        for o in siblings:
            cards.append(
                '        <a class="rp-card" href="/retreats/%s">\n'
                '          <img src="%s" alt="" loading="lazy" decoding="async">\n'
                '          <div class="rp-card-body"><h3>%s</h3><p>%s</p></div>\n'
                '        </a>'
                % (o['slug'], o.get('_photo') or '/assets/retreats/coco-ceremony.webp',
                   esc(o['title']), esc(o.get('date') or '')))
        more = ('\n  <section class="pt-sec rp-more">\n'
                '    <div class="pt-sec-bg"></div>\n'
                '    <div class="rp-in">\n      <h2>Other upcoming programs</h2>\n'
                '      <div class="rp-cards">\n%s\n      </div>\n    </div>\n  </section>\n'
                % '\n'.join(cards))

    jsonld = json.dumps({
        '@context': 'https://schema.org',
        '@type': 'Event',
        'name': title,
        'description': desc,
        'url': SITE + url,
        'image': SITE + (p.get('_card') or photo),
        **({'startDate': p['_iso_start']} if p.get('_iso_start') else {}),
        **({'endDate': p['_iso_end']} if p.get('_iso_end') else {}),
        'eventAttendanceMode': 'https://schema.org/OfflineEventAttendanceMode',
        **({'location': {'@type': 'Place', 'name': where,
                         'address': where}} if where else {}),
        'organizer': {'@type': 'Organization', 'name': 'Paititi Institute', 'url': SITE},
        **({'offers': {'@type': 'Offer', 'url': register,
                       'availability': 'https://schema.org/InStock' if not closed
                       else 'https://schema.org/SoldOut'}} if register else {}),
    }, ensure_ascii=False)

    return PAGE.format(
        site=SITE, url=url, title=esc(title),
        description=htmllib.escape(desc, quote=True),
        photo=photo,
        card=p.get('_card') or photo,
        card_w=p.get('_card_w') or p.get('_photo_w', 1200),
        card_h=p.get('_card_h') or p.get('_photo_h', 800),
        srcset=('\n           srcset="%s"' % srcset) if srcset else '',
        photo_w=p.get('_photo_w', 1200), photo_h=p.get('_photo_h', 800),
        photo_alt=esc(p.get('_photo_alt') or title),
        kicker=esc(kicker), teachers_html=teachers_html,
        facts='\n'.join(facts),
        facts_cta=facts_cta,
        body=clean_body(p.get('text_full') or p.get('text') or ''),
        video=video, gallery=gallery, more=more,
        register=htmllib.escape(register, quote=True),
        live_reg=' data-live="register"' if p.get('ID') else '',
        cta_label=cta_label,
        cta_heading=esc(p.get('_cta_heading') or 'Join us'),
        cta_note=esc(p.get('_cta_note') or
                     'Registration, full pricing and the application form are handled on '
                     'Retreat Guru, our booking system.'),
        jsonld=jsonld,
        page_js=(PAGE_JS % {'id': json.dumps(p.get('ID')), 'rg': RG}) if p.get('ID') else '',
    )


# --------------------------------------------------------------------------
# the files this page has to be wired into
# --------------------------------------------------------------------------

def write(path, content, check, changed):
    old = path.read_text(encoding='utf-8') if path.exists() else None
    if old == content:
        return
    changed.append(str(path.relative_to(ROOT)))
    if not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8')


def block_sub(text_in, begin, end, body, label):
    pat = re.compile(re.escape(begin) + r'.*?' + re.escape(end), re.S)
    new = begin + '\n' + body + '\n' + end
    if not pat.search(text_in):
        raise SystemExit('  no "%s" markers in %s' % (begin.strip(), label))
    return pat.sub(lambda _: new, text_in, count=1)


def redirects_block(programs):
    lines = [
        '# One page per program, so a single retreat can be linked to on its own.',
        '# Re-run tools/gen_retreats.py after adding or retiring a Retreat Guru',
        '# program; it rewrites everything between these two markers.',
    ]
    for p in programs:
        lines.append('/retreats/%-58s /Retreat-%s.dc.html 200' % (p['slug'], p['slug']))
    lines += [
        '# The DC runtime resolves <dc-import> as a sibling of the page URL.',
        '/retreats/SiteHeader.dc.html   /SiteHeader.dc.html  200',
        '/retreats/SiteFooter.dc.html   /SiteFooter.dc.html  200',
    ]
    return '\n'.join(lines)


def destinations_block(programs):
    """retreatguru-deeplink.js maps Retreat Guru's ?program=<id> back onto our
    own pages. Now that each program has one, an id lands on that program rather
    than on the listing."""
    rows = []
    for p in programs:
        if not p.get('ID'):
            continue
        rows.append("    %d: '/retreats/%s'," % (p['ID'], p['slug']))
    return '\n'.join(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--offline', action='store_true',
                    help='rebuild from data/retreats.json instead of fetching')
    ap.add_argument('--check', action='store_true', help='report drift, write nothing')
    args = ap.parse_args()
    check = args.check

    if args.offline or (check and SNAPSHOT.exists()):
        if not SNAPSHOT.exists():
            sys.exit('  no snapshot at %s — run once without --offline' % SNAPSHOT)
        programs = json.loads(SNAPSHOT.read_text(encoding='utf-8'))['programs']
        print('  %d programs from the snapshot' % len(programs))
    else:
        print('  fetching Retreat Guru programs…')
        programs = pull()
        if not check:
            SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
            SNAPSHOT.write_text(
                json.dumps({'source': FEED, 'programs': programs}, indent=2, ensure_ascii=False) + '\n',
                encoding='utf-8')

    extras = []
    if EXTRA.exists():
        extras = json.loads(EXTRA.read_text(encoding='utf-8'))['programs']
        print('  %d program(s) not on Retreat Guru' % len(extras))

    all_programs = programs + extras
    all_programs.sort(key=lambda p: p.get('start') or 0)

    changed = []
    from datetime import datetime, timezone
    for p in all_programs:
        p['_photo'], p['_srcset'] = mirror_photo(
            p.get('photo') or ((p.get('photo_details') or {}).get('large') or {}).get('url'),
            p['slug'], check)
        if p['_photo'] and (ROOT / p['_photo'].lstrip('/')).exists():
            try:
                from PIL import Image
                with Image.open(ROOT / p['_photo'].lstrip('/')) as im:
                    p['_photo_w'], p['_photo_h'] = im.size
            except Exception:
                pass
        p['_card'], p['_card_w'], p['_card_h'] = social_card(p['_photo'], p['slug'], check)
        for key, field in (('_iso_start', 'start'), ('_iso_end', 'end')):
            if p.get(field):
                p[key] = datetime.fromtimestamp(p[field], timezone.utc).strftime('%Y-%m-%d')

    # Pages
    for p in all_programs:
        write(ROOT / ('Retreat-%s.dc.html' % p['slug']), render(p, all_programs), check, changed)

    # A program that has come off Retreat Guru should not leave a page behind.
    live = {'Retreat-%s.dc.html' % p['slug'] for p in all_programs}
    for stale in sorted(ROOT.glob('Retreat-*.dc.html')):
        if stale.name not in live:
            changed.append('%s (removed)' % stale.name)
            if not check:
                stale.unlink()

    # _redirects
    red = ROOT / '_redirects'
    write(red, block_sub(red.read_text(encoding='utf-8'), REDIR_BEGIN, REDIR_END,
                         redirects_block(all_programs), '_redirects'), check, changed)

    # retreatguru-deeplink.js
    dl = ROOT / 'retreatguru-deeplink.js'
    write(dl, block_sub(dl.read_text(encoding='utf-8'), DEST_BEGIN, DEST_END,
                        destinations_block(all_programs), 'retreatguru-deeplink.js'),
          check, changed)

    # The widget links its cards at these slugs; anything not here falls back to
    # Retreat Guru's own program page rather than to a 404 on our side.
    slugs = ','.join(p['slug'] for p in all_programs)
    for page in ('Retreats.dc.html', 'Retreats.es.dc.html'):
        path = ROOT / page
        src = path.read_text(encoding='utf-8')
        new = re.sub(r'(rbg-widget\.html\?[^"]*?)&amp;pages=[^"&]*', r'\1', src)
        new = re.sub(r'(<iframe class="rt-frame"[^>]*?src="/rbg-widget\.html\?[^"]*?)"',
                     lambda m: m.group(1) + '&amp;pages=' + slugs + '"', new, count=1)
        write(path, new, check, changed)

    # The sitemap and the canonical tags are owned by apply_hreflang.py, which
    # reads this table. These pages have no Spanish counterpart — Retreat Guru
    # publishes them in English and registers in English — so they go in as
    # english_only rows rather than as pairs.
    #
    # Edited as text, not as a parsed-and-redumped object: the pair table is
    # hand-maintained, its columns are aligned by hand and it carries comment
    # arrays between the blocks. json.dump would reformat all 40 rows and bury
    # four added lines in a 300-line diff.
    src = PAIRS.read_text(encoding='utf-8')
    m = re.search(r'^([ \t]*)"english_only"\s*:\s*\[.*?\]', src, re.S | re.M)
    if not m:
        raise SystemExit('  no "english_only" array in tools/i18n_pairs.json')
    pad = m.group(1)
    keep = [r for r in json.loads('[' + (m.group(0).split('[', 1)[1][:-1] or '') + ']')
            if not r['file'].startswith('Retreat-')]
    rows = keep + [{'file': 'Retreat-%s.dc.html' % p['slug'], 'en': '/retreats/' + p['slug']}
                   for p in all_programs]
    body = ''.join('\n%s  { "file": %s, "en": %s },'
                   % (pad, json.dumps(r['file']), json.dumps(r['en'])) for r in rows)
    block = '%s"english_only": [%s\n%s]' % (pad, body[:-1] if body else '', pad) if rows \
        else '%s"english_only": []' % pad
    write(PAIRS, src[:m.start()] + block + src[m.end():], check, changed)

    for c in changed:
        print('  %s: %s' % ('drift' if check else 'wrote', c))
    if not changed:
        print('  everything already in step')
    if not check:
        print('\n  now run: python3 tools/apply_hreflang.py')
    return 1 if (check and changed) else 0


if __name__ == '__main__':
    raise SystemExit(main())
